FROM bcgovimages/von-image:py36-1.16-1

RUN pip install "aries_cloudagent[indy,askar,bbs]"
RUN pip install "git+https://github.com/Indicio-tech/acapy-plugin-pickup.git#egg=acapy_plugin_pickup"

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
