version: "3"
services:
  author:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.12-1.0.0
    platform: linux/amd64
    ports:
      - "3001:3001"
    environment:
      RUST_LOG: 'aries-askar::log::target=error'
    command: >
      start
        --label Author
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://author:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name author
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started
    
  second_author:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.12-1.0.0
    platform: linux/amd64
    ports:
      - "3003:3002"
    environment:
      RUST_LOG: 'aries-askar::log::target=error'
    command: >
      start
        --label SecondAuthor
        --inbound-transport http 0.0.0.0 3003
        --outbound-transport http
        --endpoint http://second_author:3003
        --admin 0.0.0.0 3002
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name SecondAuthor
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3002/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started

  endorser:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.12-1.0.0
    platform: linux/amd64
    ports:
      - "3002:3001"
    environment:
      RUST_LOG: 'aries-askar::log::target=error'
    command: >
      start
        --label Endorser
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://endorser:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name endorser
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    restart: on-failure 

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    platform: linux/amd64
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO

  example1:
    platform: linux/amd64
    container_name: controller_one
    build:
      context: ../..
    environment:
      - author=http://author:3001
      - endorser=http://endorser:3001
    volumes:
      - ../../acapy_controller:/usr/src/app/acapy_controller:z
      - ./example1.py:/usr/src/app/example1.py:ro,z
    command: python -m example1
    depends_on:
      author:
        condition: service_healthy
      endorser:
        condition: service_healthy

  example2:
    platform: linux/amd64
    container_name: controller_two
    build:
      context: ../..
    environment:
      - author=http://author:3001
      - endorser=http://endorser:3001
    volumes:
      - ../../acapy_controller:/usr/src/app/acapy_controller:z
      - ./example2.py:/usr/src/app/example2.py:ro,z
    command: python -m example2
    depends_on:
      author:
        condition: service_healthy
      endorser:
        condition: service_healthy
