#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER ${AUTHOR_AGENT_DB_USERNAME} WITH PASSWORD '${AUTHOR_AGENT_DB_PASSWORD}';

    CREATE USER ${AUTHOR_PROXY_DB_USERNAME} WITH PASSWORD '${AUTHOR_PROXY_DB_PASSWORD}';
    CREATE DATABASE ${AUTHOR_PROXY_DB} OWNER ${AUTHOR_PROXY_DB_USERNAME};
    GRANT ALL PRIVILEGES ON DATABASE ${AUTHOR_PROXY_DB} TO ${AUTHOR_PROXY_DB_USERNAME};

    CREATE USER ${ENDORSER_AGENT_DB_USERNAME} WITH PASSWORD '${ENDORSER_AGENT_DB_PASSWORD}';

    CREATE USER ${ENDORSER_PROXY_DB_USERNAME} WITH PASSWORD '${ENDORSER_PROXY_DB_PASSWORD}';
    CREATE DATABASE ${ENDORSER_PROXY_DB} OWNER ${ENDORSER_PROXY_DB_USERNAME};
    GRANT ALL PRIVILEGES ON DATABASE ${ENDORSER_PROXY_DB} TO ${ENDORSER_PROXY_DB_USERNAME};

EOSQL