version: "3"
services:
  alice:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.10.1
    ports:
      - "3001:3001"
    command: >
      start -it http 0.0.0.0 3000
        --label Alice
        -ot http
        -e http://alice:3000
        --admin 0.0.0.0 3001 --admin-insecure-mode
        --log-level debug
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_demonet_genesis
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --debug-webhooks
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 3s
      timeout: 5s
      retries: 5


  bob:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.10.1
    ports:
      - "3002:3001"
    command: >
      start -it http 0.0.0.0 3000
        --label Bob
        -ot http
        -e http://bob:3000
        --admin 0.0.0.0 3001 --admin-insecure-mode
        --log-level debug
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_demonet_genesis
        --wallet-type askar
        --wallet-name bob
        --wallet-key insecure
        --auto-provision
        --debug-webhooks
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 3s
      timeout: 5s
      retries: 5

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - ALICE=http://alice:3001
      - BOB=http://bob:3001
    volumes:
      - ./../../controller:/usr/src/app/controller:ro,z
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      alice:
        condition: service_healthy
      bob:
        condition: service_healthy
