version: "3"
services:

  proxy:
    image: ghcr.io/indicio-tech/proxy-mediator:0.1.2
    volumes:
      - ./docker/wait:/app/wait:z
    environment:
      PORT: 3000
      ENDPOINT: http://proxy:3000
      LOG_LEVEL: DEBUG
      WAIT_BEFORE_HOSTS: 3
      WAIT_HOSTS: ediator:3000
      WAIT_HOSTS_TIMEOUT: 30
      WAIT_SLEEP_INTERVAL: 1
      WAIT_HOST_CONNECT_TIMEOUT: 10
    entrypoint: /bin/sh -c '/app/wait && python -m proxy_mediator "$$@"' --

  setup:
    image: ghcr.io/indicio-tech/proxy-mediator-setup:0.1.2
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=proxy:3000,alice:3000
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - PROXY=http://proxy:3000
      - AGENT=http://alice:3001
      - MEDIATOR=http://mediator:3001
    depends_on:
      - proxy
      - alice

  alice:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.9.0
    ports:
      - "3001:3001"
    command: >
      start
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://alice:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --webhook-url http://webhook-listener:8080
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --public-invites
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      webhook-listener:
        condition: service_started
      tails:
        condition: service_started

  mediator:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.9.0
    ports:
      - "3003:3001"
    command: >
      start
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://mediator:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --webhook-url http://webhook-listener:8080
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name mediator
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --webhook-url http://webhook-listener:8080
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      webhook-listener:
        condition: service_started

  bob:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.9.0
    ports:
      - "3002:3001"
    command: >
      start
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://bob:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --webhook-url http://webhook-listener:8080
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name bob
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --webhook-url http://webhook-listener:8080
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      webhook-listener:
        condition: service_started

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - ALICE=http://alice:3001
      - BOB=http://bob:3001
      - MEDIATOR=http://mediator:3001
    volumes:
      - ../../controller:/usr/src/app/controller:z,ro
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      alice:
        condition: service_healthy
      bob:
        condition: service_healthy
      mediator:
        condition: service_healthy
      setup:
        condition: service_completed_successfully

  webhook-listener:
    image: mendhak/http-https-echo:18
    environment:
      - HTTP_PORT=8080

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO
