version: "3"
services:

  proxy:
    image: ghcr.io/indicio-tech/proxy-mediator:0.1.2
    environment:
      PORT: 3000
      ENDPOINT: http://proxy:3000
      LOG_LEVEL: DEBUG
    depends_on:
      mediator:
        condition: service_healthy
      alice:
        condition: service_healthy
      reverse-proxy:
        condition: service_started

  setup:
    image: ghcr.io/indicio-tech/proxy-mediator-setup:0.1.2
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=proxy:3000,alice:3000
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - PROXY=http://proxy:3000
      - AGENT=http://alice:3001
      # - MEDIATOR=http://mediator:3001
      - MEDIATOR_INVITE=https://ys40cgl5r2.execute-api.us-east-1.amazonaws.com/Prod/message?oob=eyJAaWQiOiIwMTk3Y2Y4NS0yMzFlLTRlZDItYTNjMi0zZTBlNmVmYzk3OGQiLCJAdHlwZSI6Imh0dHBzOi8vZGlkY29tbS5vcmcvb3V0LW9mLWJhbmQvMS4xL2ludml0YXRpb24iLCJoYW5kc2hha2VfcHJvdG9jb2xzIjpbImh0dHBzOi8vZGlkY29tbS5vcmcvZGlkZXhjaGFuZ2UvMS4wIl0sInNlcnZpY2VzIjpbeyJpZCI6IiNpbmxpbmUiLCJ0eXBlIjoiZGlkLWNvbW11bmljYXRpb24iLCJyZWNpcGllbnRLZXlzIjpbImRpZDprZXk6ejZNa3R3ZVVBdUJFYXB6d3hoWTdQS2JzdDNhR0xoWGhqcUU0VkNTM1lGMVBMdmU3Il0sInNlcnZpY2VFbmRwb2ludCI6Imh0dHBzOi8veXM0MGNnbDVyMi5leGVjdXRlLWFwaS51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9Qcm9kL21lc3NhZ2UifSx7ImlkIjoiI2lubGluZSIsInR5cGUiOiJkaWQtY29tbXVuaWNhdGlvbiIsInJlY2lwaWVudEtleXMiOlsiZGlkOmtleTp6Nk1rdHdlVUF1QkVhcHp3eGhZN1BLYnN0M2FHTGhYaGpxRTRWQ1MzWUYxUEx2ZTciXSwic2VydmljZUVuZHBvaW50Ijoid3M6Ly9ERE0tUHJvZC0xMzMxOTUzNzEudXMtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29tL3dzIn1dLCJhY2NlcHQiOlsiZGlkY29tbS9haXAxIiwiZGlkY29tbS9haXAyO2Vudj1yZmMxOSJdLCJsYWJlbCI6IkNsb3VkIE1lZGlhdG9yIn0=
    depends_on:
      - proxy
      - alice

  alice:
    #image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.9.0
    image: ghcr.io/indicio-tech/aries-cloudagent-python:py3.9-fix-keylist-update-response-race
    ports:
      - "3001:3001"
    command: >
      start
        --label Alice
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://alice:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --webhook-url http://webhook-listener:8080
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --public-invites
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      webhook-listener:
        condition: service_started
      tails:
        condition: service_started

  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:z
    environment:
      MEDIATOR: mediator
      HTTP_PORT: 3000
      WS_PORT: 3002
    ports:
      - 8080:80
    depends_on:
      - mediator

  mediator:
    # image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.9.0
    image: ghcr.io/indicio-tech/aries-cloudagent-python:py3.9-fix-keylist-update-response-race
    ports:
      - "3003:3001"
    command: >
      start
        --label Mediator
        --inbound-transport http 0.0.0.0 3000
        --inbound-transport ws 0.0.0.0 3002
        --outbound-transport http
        --endpoint http://reverse-proxy ws://reverse-proxy/ws
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --webhook-url http://webhook-listener:8080
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name mediator
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --webhook-url http://webhook-listener:8080
        --monitor-revocation-notification
        --auto-accept-requests
        --open-mediation
        --enable-undelivered-queue
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      webhook-listener:
        condition: service_started

  bob:
    # image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.9.0
    image: ghcr.io/indicio-tech/aries-cloudagent-python:py3.9-fix-keylist-update-response-race
    ports:
      - "3002:3001"
    command: >
      start
        --label Bob
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://bob:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --webhook-url http://webhook-listener:8080
        --tails-server-base-url http://tails:6543
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --wallet-type askar
        --wallet-name bob
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --webhook-url http://webhook-listener:8080
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      webhook-listener:
        condition: service_started

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - ALICE=http://alice:3001
      - BOB=http://bob:3001
      - MEDIATOR=http://mediator:3001
    volumes:
      - ../../controller:/usr/src/app/controller:z,ro
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      alice:
        condition: service_healthy
      bob:
        condition: service_healthy
      mediator:
        condition: service_healthy
      setup:
        condition: service_completed_successfully

  webhook-listener:
    image: mendhak/http-https-echo:18
    environment:
      - HTTP_PORT=8080

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO
