name: Code Quality Check

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format and Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@25.1.0
        with:
          src: "./acapy_controller ./examples"
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.3.5
          src: "./acapy_controller ./examples"
